

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"


[[test.validator.clone]] # switchboardProgramId
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # switchboardProgramDataAddress
address = "J4CArpsbrZqu1axqQ4AnrqREs3jwoyA1M5LMiQQmAzB9"

[[test.validator.clone]] # switchboardIdlAddress
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # switchboardProgramState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # switchboardVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # switchboardMint
address = "So11111111111111111111111111111111111111112"

[[test.validator.clone]] # tokenWallet
address = "4BJK4DebV1LvTdxaZ4cxaYXqLrLVH2zRmLSUGMCGpUiS"

[[test.validator.clone]] # oracleQueue
address = "3sUQ7MhW8S71RS17HxJ3DZX8z9DGGASsWQxh2EsgF1vW"

[[test.validator.clone]] # oracleQueueAuthority
address = "84jdiqYNJiUFtTucc817VmowyznsDwcmskyD7stu3Duj"

[[test.validator.clone]] # oracleQueueBuffer
address = "DEf7i2EA4qMBzbP14mrgq3gAwnEuWAj3jVqbb9YR14UJ"

[[test.validator.clone]] # crank
address = "6pWDDGkpHkZRqjp2Koa4oEzQLtrNXZgPD1u3fr7H2vu3"

[[test.validator.clone]] # crankBuffer
address = "3yYYmVjPGgAYGv5zUegaUhEEAEkfpNrxF5bfiWE8JQni"

[[test.validator.clone]] # oracle
address = "Cm12dL7cHpbqfYPr4nYCG7Sfn9kpSYnJwBb7KxmqMoBc"

[[test.validator.clone]] # oracleAuthority
address = "84jdiqYNJiUFtTucc817VmowyznsDwcmskyD7stu3Duj"

[[test.validator.clone]] # oracleEscrow
address = "VxopvtrNBFKvuWp5iSYdEHVfsEzK4eEzdRfcPsUY4Db"

[[test.validator.clone]] # oraclePermissions
address = "BraqxMpzKpsaepZSH8Z7fAGvUaVbGeLPMi2vkCsDGAt"